### PR TITLE
Add cycle-markdown-driver

### PR DESCRIPTION
**Pull request by takashi**

### CODE REVIEW

**Comment by staltz** [comment]
Hi, thanks for submitting. Because the markdown processing is pure and there isn't any async/remote/external/impure target involved, your driver is not really a driver, and I would prefer not to include it in the list. Since it just converts the callback API of `marked`, we don't even need a library, you can just do 

``` js
const markdown$ = raw$.flatMap(raw =>
  Rx.Observable.fromCallback(marked)(raw)
);
```

Sorry.

**Comment by takashi** [comment]
@staltz 
hi, thanks for advice! since I'm new to cycle.js, sorry for misunderstand what a driver is.
I'll fix my lib. can i submit pr after i fixed ? 

thanks.

**Comment by staltz** [comment]
Hi, check here what drivers are and how to build them: http://cycle.js.org/drivers.html

And I'd recommend not making a library since you can use those 3 lines of code already.
If you make a library, then it will be related to RxJS, not about Cycle, so I recommend sending it to the RxJS community.

**Comment by takashi** [comment]
> And I'd recommend not making a library since you can use those 3 lines of code already.

yep i agree with you. i try to implement this way in my app 
thanks again to advising me!

**Comment by staltz** [comment]
Thanks for an active being part of the community

**Pull request closed without merging**
