### PR TITLE
Update links to resources and update star counts

### LINKED ISSUE #97: Some of the resources are moved and star counts outdated
This is an awesome list. However, some of the resources like Cycle.js examples are moved and the amount of stars do not match the actual amounts anymore. I think this is especially unwanted for create-cycle-app as it does not get enough visibility in this list at the moment. 

I suggest we do:
- Go through the list, update all the links that are outdated and/or missing
- Add missing resources to the list if there are some
- Update the amounts of stars or remove the star amounts from this list (???)

I volunteer for doing the manual work needed in order to fix this.

### PR DESCRIPTION
**Pull request by olpeh**
- I went through all the links and updated those that were broken/moved
- Updated amount of stars for each repository
- Added a few important resources
- Fixed a few style issues

Fixes and closes #97

### CODE REVIEW

**Comment by staltz** [comment]
Looks good to me! :)

**Comment by artfuldev** [comment]
@jvanbruegge @TylorS @Widdershin @vic we need to add @olpeh to the community. 😃

**Comment by Widdershin** [comment]
Done! Thanks for this contribution @olpeh.

Please stop by our introductions thread and introduce yourself!

https://github.com/cyclejs-community/README/issues/7

**Comment by Widdershin** [comment]
I've also invited you to be a collaborator on this repository, which allows you to review and merge pull requests. 😄

**Comment by olpeh** [comment]
Thank you! Awesome to be part of the community :smile:

**Pull request merged**
