### PR TITLE
renamed redux-cycle-middleware into redux-cycles

### PR DESCRIPTION
**Pull request by SteveALee**

### CODE REVIEW

**Comment by nickbalestra** [comment]
Thanks @SteveALee !

**Comment by SteveALee** [comment]
@nickbalestra can you merge this as I can't?

GitHub seems to give no information of access permissions. For what ever reason I don't have write access even though am a member.

**Comment by Widdershin** [comment]
I've added both of you as collaborators, you should be able to review and merge other people's pull requests now.

😄

**Comment by nickbalestra** [comment]
Sweet thanks!

**Pull request merged**
