### PR TITLE
Add cyclejs-sortable

### PR DESCRIPTION
**Pull request by jvanbruegge**

### CODE REVIEW

**Comment by staltz** [comment]
Thanks!

**Comment by artfuldev** [comment]
Which is the main repo? The one under SuperManitu, or the one under cyclejs-community?

**Comment by jvanbruegge** [comment]
As you can see, the one under SuperManitu is a fork used to work on it. The link is correct.

**Comment by artfuldev** [comment]
The name in the list is referencing the fork, but the link is to the main repo... Why so? This is deviating from most other repos where the names and the links refer to the same repo. It is kind of misleading, in a sense. I wonder if you could edit it.

**Comment by artfuldev** [comment]
Even in [the documentation](https://cyclejs-community.github.io/cyclejs-sortable/), the fork is pointed to. It was very confusing to me when I first looked at it, and the documentation. Why this duality?

**Comment by jvanbruegge** [comment]
The repo was transfered lately. I use the fork to maintain it. Not all links are updated. But fork and repo have same content anyway

**Comment by artfuldev** [comment]
Also, I'm sorry that I failed to mention: this is something wonderful that you've built. Awesome! 👍

**Comment by jvanbruegge** [comment]
Thanks, i will look through your PR once at home. In this list i want to keep the link as it is, because you can see who is maintaining it.

**Comment by artfuldev** [comment]
Not a matter.

But just to point out, we can have a list of maintainers in the project README instead, that will achieve the same effect. If pointing to a fork, why move it to cyclejs-community at all, right? Just saying. BTW we could've added the fork to the list instead, too. What I was talking about was making things consistent. Whatever works. 👍

**Pull request merged**
